# Configurações do banco de dados
spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: root

# Configurações do JPA
spring.jpa:
  show-sql: true
  properties:
    hibernate.format_sql: true

# Configuração do tratamento de erros
server.error:
  include-stacktrace: never

# Configurações de segurança e token
api.security:
  token.secret: ${JWT_SECRET:12345678}

# Configuração do servidor
server.port: 8080

# Configuração do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true

# Configuração da negociação de conteúdo
spring.mvc.contentnegotiation:
  favor-path-extension: true
  favor-parameter: false
