global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-spring-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["34.228.217.61:8080"]
        labels:
          application: "api-spring"
