name: DEV Java CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B clean -DskipTests --file pom.xml
      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PUBLIC_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/api/${{ secrets.REMOTE_USER }}
          EXCLUDE: "infra"
          
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.AWS_PUBLIC_KEY }}
          port: 22
          script: |
            export PORT=8080
            chmod +x start.sh
            ./start.sh
            nohup java -Dspring.profiles.active=prod -DDATASOURCE_URL=jdbc:mysql://${{ secrets.DATASOURCE_URL }}/vollmed_api -DDATASOURCE_USERNAME=${{ secrets.DATASOURCE_PASSWORD }} -DDATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} -jar target/api-0.0.1-SNAPSHOT.jar > out.txt 2>&1 &
